version: '3.9'
services:
  tim:
    container_name: TIM
    build:
      context: .
    ports:
      - 8085:8085
    networks:
      - tim
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - jwt-integration.signature.key-store-password=defaultpassword
      

networks:
  tim:
    driver: bridge
